excluded:
  - Pods
  - Carthage
  - fastlane

included:
  - Sources
  - Tests

opt_in_rules:
  - empty_count
  - explicit_self
  - implicit_return
  - sorted_imports

disabled_rules:
  - colon
  - comma
  - control_statement

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

identifier_name:
  excluded:
    - id
    - URL
    - GlobalAPIKey
  allowed_symbols: ["_", "$"]
  validates_start_with_lowercase: false

type_name:
  min_length: 3
  max_length: 40
  excluded:
    - id
    - URL

custom_rules:
  todo:
    included: ".*"
    name: "TODOs and FIXMEs"
    regex: "(TODO|FIXME|todo|fixme)"
    message: "TODOs and FIXMEs should be avoided"
    severity: warning

excluded_files:
  - "Sources/AppDelegate.swift":
    - force_unwrapping
    - trailing_whitespace
  - "Tests/*":
    - force_try

