# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CloudVault' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CloudVault

    pod 'AWSMobileClient'
    pod 'AWSPinpoint'

  target 'CloudVaultTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CloudVaultUITests' do
    # Pods for testing
  end

end
